api_version: 1
auto_merge:
  - dependency: optic14n
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: govuk_app_config
    allowed_semver_bumps:
      - patch
      - minor
  - dependency: rubocop-govuk
    allowed_semver_bumps:
      - patch
      - minor
