inherit_gem:
  rubocop-govuk:
    - "config/default.yml"
    - "config/rspec.yml"

inherit_mode:
  merge:
    - Exclude

# This repo has a pattern of using doubles to mock DB objects,
# instead of creating them properly in a test DB. Since fields
# of a model like Site are defined dynamically when the records
# are loaded, it's not possible to use "instance_double" to mock
# them - this will lead to an error about a non-existent attribute.
#
# https://github.com/alphagov/bouncer/pull/274#discussion_r510991055
RSpec/VerifiedDoubles:
  Exclude:
    - "spec/units/bouncer/app_spec.rb"
    - "spec/units/host_spec.rb"
    - "spec/units/mapping_spec.rb"
    - "spec/units/organisation_spec.rb"
    - "spec/units/site_spec.rb"
